/* Generated By:JavaCC: Do not edit this line. EasyAnimParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EasyAnimParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 28;
  /** RegularExpression Id. */
  int FLOAT = 29;
  /** RegularExpression Id. */
  int LPAR = 30;
  /** RegularExpression Id. */
  int RPAR = 31;
  /** RegularExpression Id. */
  int STRING = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"Animation\"",
    "\"Duration:\"",
    "\"SubAnimations\"",
    "\"Poses\"",
    "\";\"",
    "\"Add\"",
    "\"at\"",
    "\"frame\"",
    "\"Pose\"",
    "\"HEAD:\"",
    "\"CHEST:\"",
    "\"R SHOULDER:\"",
    "\"L SHOULDER:\"",
    "\"UPPER R ARM:\"",
    "\"LOWER R ARM:\"",
    "\"UPPER L ARM:\"",
    "\"LOWER L ARM:\"",
    "\"R HIP:\"",
    "\"L HIP:\"",
    "\"UPPER R LEG:\"",
    "\"LOWER R LEG:\"",
    "\"UPPER L LEG:\"",
    "\"LOWER L LEG:\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"frames\"",
    "<NUM>",
    "<FLOAT>",
    "\"{\"",
    "\"}\"",
    "<STRING>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 37>",
    "<token of kind 38>",
  };

}
