/* Generated by JTB 1.4.7 */
package poseParser.visitor;

import poseParser.syntaxtree.*;

public interface IVoidArguVisitor<A> {

  public void visit(final NodeChoice n, final A argu);

  public void visit(final NodeList n, final A argu);

  public void visit(final NodeListOptional n, final A argu);

  public void visit(final NodeOptional n, final A argu);

  public void visit(final NodeSequence n, final A argu);

  public void visit(final NodeTCF n, final A argu);

  public void visit(final NodeToken n, final A argu);

  public void visit(final Pose n, final A argu);

  public void visit(final PoseDef n, final A argu);

  public void visit(final BoneName n, final A argu);

  public void visit(final BoneDef n, final A argu);

  public void visit(final Position n, final A argu);

  public void visit(final PoseName n, final A argu);

}
