/* Generated by JTB 1.4.7 */
package poseParser.visitor;

import poseParser.syntaxtree.*;

public interface IVoidVisitor {

  public void visit(final NodeChoice n);

  public void visit(final NodeList n);

  public void visit(final NodeListOptional n);

  public void visit(final NodeOptional n);

  public void visit(final NodeSequence n);

  public void visit(final NodeTCF n);

  public void visit(final NodeToken n);

  public void visit(final Pose n);

  public void visit(final PoseDef n);

  public void visit(final BoneName n);

  public void visit(final BoneDef n);

  public void visit(final Position n);

  public void visit(final PoseName n);

}
