/* Generated by JTB 1.4.7 */
package parser.visitor;

import parser.syntaxtree.*;
import java.util.*;

public class DepthFirstVoidArguVisitor<A> implements IVoidArguVisitor<A> {


  public void visit(final NodeChoice n, final A argu) {
    n.choice.accept(this, argu);
    return;
  }

  public void visit(final NodeList n, final A argu) {
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      e.next().accept(this, argu);
    }
    return;
  }

  public void visit(final NodeListOptional n, final A argu) {
    if (n.present()) {
      for (final Iterator<INode> e = n.elements(); e.hasNext();) {
        e.next().accept(this, argu);
        }
      return;
    } else
      return;
  }

  public void visit(final NodeOptional n, final A argu) {
    if (n.present()) {
      n.node.accept(this, argu);
      return;
    } else
      return;
  }

  public void visit(final NodeSequence n, final A argu) {
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      e.next().accept(this, argu);
    }
    return;
  }

  public void visit(final NodeTCF n, final A argu) {
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return;
  }

  public void visit(final NodeToken n, final A argu) {
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return;
  }

  public void visit(final Animation n, final A argu) {
    // f0 -> "Animation"
    n.f0.accept(this, argu);
    // f1 -> AnimationName()
    n.f1.accept(this, argu);
    // f2 -> AnimationDef()
    n.f2.accept(this, argu);
  }

  public void visit(final AnimationDef n, final A argu) {
    // f0 -> "Duration:"
    n.f0.accept(this, argu);
    // f1 -> Duration()
    n.f1.accept(this, argu);
    // f2 -> ( #0 "SubAnimations" #1 <LPAR>
    // .. .. . #2 ( SubAnimation() )+
    // .. .. . #3 <RPAR> )?
    n.f2.accept(this, argu);
    // f3 -> "Poses"
    n.f3.accept(this, argu);
    // f4 -> <LPAR>
    n.f4.accept(this, argu);
    // f5 -> ( Pose() )+
    n.f5.accept(this, argu);
    // f6 -> <RPAR>
    n.f6.accept(this, argu);
    // f7 -> ( %0 ";"
    // .. .. | %1 <EOF> )
    n.f7.accept(this, argu);
  }

  public void visit(final SubAnimation n, final A argu) {
    // f0 -> "Add"
    n.f0.accept(this, argu);
    // f1 -> "Animation"
    n.f1.accept(this, argu);
    // f2 -> AnimationName()
    n.f2.accept(this, argu);
    // f3 -> "at"
    n.f3.accept(this, argu);
    // f4 -> "frame"
    n.f4.accept(this, argu);
    // f5 -> Frame()
    n.f5.accept(this, argu);
    // f6 -> AnimationDef()
    n.f6.accept(this, argu);
  }

  public void visit(final Pose n, final A argu) {
    // f0 -> "Add"
    n.f0.accept(this, argu);
    // f1 -> "Pose"
    n.f1.accept(this, argu);
    // f2 -> PoseName()
    n.f2.accept(this, argu);
    // f3 -> "at"
    n.f3.accept(this, argu);
    // f4 -> "frame"
    n.f4.accept(this, argu);
    // f5 -> Frame()
    n.f5.accept(this, argu);
    // f6 -> PoseDef()
    n.f6.accept(this, argu);
  }

  public void visit(final PoseDef n, final A argu) {
    // f0 -> <LPAR>
    n.f0.accept(this, argu);
    // f1 -> ( #0 BoneName() #1 BoneDef() )+
    n.f1.accept(this, argu);
    // f2 -> <RPAR>
    n.f2.accept(this, argu);
  }

  public void visit(final BoneName n, final A argu) {
    // f0 -> ( %00 "HEAD:"
    // .. .. | %01 "CHEST:"
    // .. .. | %02 "R SHOULDER:"
    // .. .. | %03 "L SHOULDER:"
    // .. .. | %04 "UPPER R ARM:"
    // .. .. | %05 "LOWER R ARM:"
    // .. .. | %06 "UPPER L ARM:"
    // .. .. | %07 "LOWER L ARM:"
    // .. .. | %08 "R HIP:"
    // .. .. | %09 "L HIP:"
    // .. .. | %10 "UPPER R LEG:"
    // .. .. | %11 "LOWER R LEG:"
    // .. .. | %12 "UPPER L LEG:"
    // .. .. | %13 "LOWER L LEG:" )
    n.f0.accept(this, argu);
  }

  public void visit(final BoneDef n, final A argu) {
    // f0 -> Position()
    n.f0.accept(this, argu);
    // f1 -> ","
    n.f1.accept(this, argu);
    // f2 -> Position()
    n.f2.accept(this, argu);
  }

  public void visit(final Frame n, final A argu) {
    // f0 -> <NUM>
    n.f0.accept(this, argu);
  }

  public void visit(final Position n, final A argu) {
    // f0 -> "("
    n.f0.accept(this, argu);
    // f1 -> <FLOAT>
    n.f1.accept(this, argu);
    // f2 -> ","
    n.f2.accept(this, argu);
    // f3 -> <FLOAT>
    n.f3.accept(this, argu);
    // f4 -> ","
    n.f4.accept(this, argu);
    // f5 -> <FLOAT>
    n.f5.accept(this, argu);
    // f6 -> ")"
    n.f6.accept(this, argu);
  }

  public void visit(final AnimationName n, final A argu) {
    // f0 -> ( <STRING> )+
    n.f0.accept(this, argu);
  }

  public void visit(final PoseName n, final A argu) {
    // f0 -> ( <STRING> )+
    n.f0.accept(this, argu);
  }

  public void visit(final Duration n, final A argu) {
    // f0 -> <NUM>
    n.f0.accept(this, argu);
    // f1 -> "frames"
    n.f1.accept(this, argu);
  }

}
