/* Generated by JTB 1.4.7 */
package parser.visitor;

import parser.syntaxtree.*;

public interface IRetArguVisitor<R, A> {

  public R visit(final NodeChoice n, final A argu);

  public R visit(final NodeList n, final A argu);

  public R visit(final NodeListOptional n, final A argu);

  public R visit(final NodeOptional n, final A argu);

  public R visit(final NodeSequence n, final A argu);

  public R visit(final NodeTCF n, final A argu);

  public R visit(final NodeToken n, final A argu);

  public R visit(final Animation n, final A argu);

  public R visit(final AnimationDef n, final A argu);

  public R visit(final SubAnimation n, final A argu);

  public R visit(final Pose n, final A argu);

  public R visit(final PoseDef n, final A argu);

  public R visit(final BoneName n, final A argu);

  public R visit(final BoneDef n, final A argu);

  public R visit(final Frame n, final A argu);

  public R visit(final Position n, final A argu);

  public R visit(final AnimationName n, final A argu);

  public R visit(final PoseName n, final A argu);

  public R visit(final Duration n, final A argu);

}
