/* Generated By:JavaCC: Do not edit this line. PoseParserConstants.java */
package poseParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PoseParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FLOAT = 19;
  /** RegularExpression Id. */
  int LPAR = 20;
  /** RegularExpression Id. */
  int RPAR = 21;
  /** RegularExpression Id. */
  int STRING = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"Pose\"",
    "\"HEAD:\"",
    "\"CHEST:\"",
    "\"R SHOULDER:\"",
    "\"L SHOULDER:\"",
    "\"UPPER R ARM:\"",
    "\"LOWER R ARM:\"",
    "\"UPPER L ARM:\"",
    "\"LOWER L ARM:\"",
    "\"R HIP:\"",
    "\"L HIP:\"",
    "\"UPPER R LEG:\"",
    "\"LOWER R LEG:\"",
    "\"UPPER L LEG:\"",
    "\"LOWER L LEG:\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "<FLOAT>",
    "\"{\"",
    "\"}\"",
    "<STRING>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 27>",
    "<token of kind 28>",
  };

}
