/* Generated By:JavaCC: Do not edit this line. PoseParserTokenManager.java */
package poseParser;
import poseParser.visitor.*;
import java.io.FileInputStream;
import poseParser.syntaxtree.*;

/** Token Manager. */
public class PoseParserTokenManager implements PoseParserConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0xfffeL) != 0L)
         {
            jjmatchedKind = 22;
            return 3;
         }
         if ((active0 & 0x60000L) != 0L)
            return 3;
         return -1;
      case 1:
         if ((active0 & 0xf3ceL) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 1;
            return 3;
         }
         if ((active0 & 0xc30L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         return -1;
      case 2:
         if ((active0 & 0xf3ceL) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 2;
            return 3;
         }
         if ((active0 & 0xc30L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         return -1;
      case 3:
         if ((active0 & 0xf3ccL) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 3;
            return 3;
         }
         if ((active0 & 0x2L) != 0L)
            return 3;
         if ((active0 & 0xc30L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         return -1;
      case 4:
         if ((active0 & 0xf3c8L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 4;
            return 3;
         }
         if ((active0 & 0xc30L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         return -1;
      case 5:
         if ((active0 & 0xf3c0L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0xc30L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         return -1;
      case 6:
         if ((active0 & 0xf3c0L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x30L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         return -1;
      case 7:
         if ((active0 & 0xf3c0L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x30L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         return -1;
      case 8:
         if ((active0 & 0xf3c0L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x30L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         return -1;
      case 9:
         if ((active0 & 0xf3c0L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x30L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         return -1;
      case 10:
         if ((active0 & 0xf3c0L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x30L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 40:
         return jjStartNfaWithStates_0(0, 17, 3);
      case 41:
         return jjStartNfaWithStates_0(0, 18, 3);
      case 44:
         return jjStopAtPos(0, 16);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x8L);
      case 72:
         return jjMoveStringLiteralDfa1_0(0x4L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0xaaa0L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x2L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x410L);
      case 85:
         return jjMoveStringLiteralDfa1_0(0x5140L);
      case 123:
         return jjStopAtPos(0, 20);
      case 125:
         return jjStopAtPos(0, 21);
      default :
         return jjMoveNfa_0(4, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa2_0(active0, 0xc30L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x4L);
      case 72:
         return jjMoveStringLiteralDfa2_0(active0, 0x8L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0xa280L);
      case 80:
         return jjMoveStringLiteralDfa2_0(active0, 0x5140L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x4L);
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x8L);
      case 72:
         return jjMoveStringLiteralDfa3_0(active0, 0xc00L);
      case 80:
         return jjMoveStringLiteralDfa3_0(active0, 0x5140L);
      case 83:
         return jjMoveStringLiteralDfa3_0(active0, 0x30L);
      case 87:
         return jjMoveStringLiteralDfa3_0(active0, 0xa280L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa4_0(active0, 0x4L);
      case 69:
         return jjMoveStringLiteralDfa4_0(active0, 0xf3c0L);
      case 72:
         return jjMoveStringLiteralDfa4_0(active0, 0x30L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0xc00L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x8L);
      case 101:
         if ((active0 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(3, 1, 3);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x4L) != 0L)
            return jjStopAtPos(4, 2);
         break;
      case 79:
         return jjMoveStringLiteralDfa5_0(active0, 0x30L);
      case 80:
         return jjMoveStringLiteralDfa5_0(active0, 0xc00L);
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0xf3c0L);
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0x8L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa6_0(active0, 0xf3c0L);
      case 58:
         if ((active0 & 0x8L) != 0L)
            return jjStopAtPos(5, 3);
         else if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(5, 10);
         else if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(5, 11);
         break;
      case 85:
         return jjMoveStringLiteralDfa6_0(active0, 0x30L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 76:
         return jjMoveStringLiteralDfa7_0(active0, 0xc330L);
      case 82:
         return jjMoveStringLiteralDfa7_0(active0, 0x30c0L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa8_0(active0, 0xf3c0L);
      case 68:
         return jjMoveStringLiteralDfa8_0(active0, 0x30L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa9_0(active0, 0x3c0L);
      case 69:
         return jjMoveStringLiteralDfa9_0(active0, 0x30L);
      case 76:
         return jjMoveStringLiteralDfa9_0(active0, 0xf000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa10_0(active0, 0xf000L);
      case 82:
         return jjMoveStringLiteralDfa10_0(active0, 0x3f0L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x10L) != 0L)
            return jjStopAtPos(10, 4);
         else if ((active0 & 0x20L) != 0L)
            return jjStopAtPos(10, 5);
         break;
      case 71:
         return jjMoveStringLiteralDfa11_0(active0, 0xf000L);
      case 77:
         return jjMoveStringLiteralDfa11_0(active0, 0x3c0L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x40L) != 0L)
            return jjStopAtPos(11, 6);
         else if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(11, 7);
         else if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(11, 8);
         else if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(11, 9);
         else if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(11, 12);
         else if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(11, 13);
         else if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(11, 14);
         else if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(11, 15);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0x0L, 0x204130100000000L
};
static final long[] jjbitVec1 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 16;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 4:
                  if ((0x83ff438200000000L & l) != 0L)
                  {
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAdd(3);
                  }
                  else if (curChar == 47)
                     jjAddStates(0, 1);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 19)
                        kind = 19;
                     jjCheckNAddTwoStates(0, 1);
                  }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  jjCheckNAddTwoStates(0, 1);
                  break;
               case 1:
                  if (curChar == 46)
                     jjCheckNAdd(2);
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  jjCheckNAdd(2);
                  break;
               case 3:
                  if ((0x83ff438200000000L & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAdd(3);
                  break;
               case 5:
                  if (curChar == 47)
                     jjCheckNAddStates(2, 4);
                  break;
               case 6:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(2, 4);
                  break;
               case 7:
                  if ((0x2400L & l) != 0L && kind > 27)
                     kind = 27;
                  break;
               case 8:
                  if (curChar == 10 && kind > 27)
                     kind = 27;
                  break;
               case 9:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 10:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(11, 12);
                  break;
               case 11:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(11, 12);
                  break;
               case 12:
                  if (curChar == 42)
                     jjAddStates(5, 6);
                  break;
               case 13:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(14, 12);
                  break;
               case 14:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(14, 12);
                  break;
               case 15:
                  if (curChar == 47 && kind > 28)
                     kind = 28;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 4:
               case 3:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAdd(3);
                  break;
               case 6:
                  jjAddStates(2, 4);
                  break;
               case 11:
                  jjCheckNAddTwoStates(11, 12);
                  break;
               case 13:
               case 14:
                  jjCheckNAddTwoStates(14, 12);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 4:
               case 3:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAdd(3);
                  break;
               case 6:
                  if ((jjbitVec1[i2] & l2) != 0L)
                     jjAddStates(2, 4);
                  break;
               case 11:
                  if ((jjbitVec1[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(11, 12);
                  break;
               case 13:
               case 14:
                  if ((jjbitVec1[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(14, 12);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 16 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   5, 10, 6, 7, 9, 13, 15, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", "\120\157\163\145", "\110\105\101\104\72", "\103\110\105\123\124\72", 
"\122\40\123\110\117\125\114\104\105\122\72", "\114\40\123\110\117\125\114\104\105\122\72", 
"\125\120\120\105\122\40\122\40\101\122\115\72", "\114\117\127\105\122\40\122\40\101\122\115\72", 
"\125\120\120\105\122\40\114\40\101\122\115\72", "\114\117\127\105\122\40\114\40\101\122\115\72", "\122\40\110\111\120\72", 
"\114\40\110\111\120\72", "\125\120\120\105\122\40\122\40\114\105\107\72", 
"\114\117\127\105\122\40\122\40\114\105\107\72", "\125\120\120\105\122\40\114\40\114\105\107\72", 
"\114\117\127\105\122\40\114\40\114\105\107\72", "\54", "\50", "\51", null, "\173", "\175", null, null, null, null, null, null, 
null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x7fffffL, 
};
static final long[] jjtoSkip = {
   0x1f800000L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[16];
static private final int[] jjstateSet = new int[32];
static protected char curChar;
/** Constructor. */
public PoseParserTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public PoseParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 16; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
